import nodemailer from 'nodemailer';
import {db} from '../src/server/db';
import {reconcile} from '../src/server/papi';
import {release,audit,type OrderRow} from '../src/server/commerce';
async function cycle(){
 await db().transaction(async tx=>{const rows=await tx.query<OrderRow>("SELECT * FROM orders WHERE payment_started=false AND released=false AND created_at<now()-interval '1 hour' FOR UPDATE SKIP LOCKED");for(const row of rows.rows){await release(tx,row);row.data.status='Annulée';await tx.query("UPDATE orders SET payment_status='expired',data=$2 WHERE id=$1",[row.id,JSON.stringify(row.data)]);await audit(tx,'worker','order.abandoned',row.id);}});
 const pending=await db().query<{id:string}>("SELECT id FROM orders WHERE payment_status IN ('pending','failed') AND payment_started=true ORDER BY created_at LIMIT 100");
 for(const row of pending.rows)try{await reconcile(row.id);}catch{console.error(JSON.stringify({level:'error',event:'payment.reconcile_failed',orderId:row.id}));}
 if(process.env.SMTP_HOST&&process.env.MAIL_FROM){const transport=nodemailer.createTransport({host:process.env.SMTP_HOST,port:Number(process.env.SMTP_PORT||587),secure:process.env.SMTP_PORT==='465',requireTLS:process.env.SMTP_PORT!=='465',auth:process.env.SMTP_USER?{user:process.env.SMTP_USER,pass:process.env.SMTP_PASSWORD}:undefined,connectionTimeout:10000,socketTimeout:15000});
 for(let i=0;i<50;i++){const worked=await db().transaction(async tx=>{const row=(await tx.query<{id:string;recipient:string;subject:string;body:string;attempts:number}>('SELECT * FROM outbox WHERE sent_at IS NULL AND available_at<=now() ORDER BY available_at FOR UPDATE SKIP LOCKED LIMIT 1')).rows[0];if(!row)return false;try{await transport.sendMail({from:process.env.MAIL_FROM,to:row.recipient,subject:row.subject,text:row.body,messageId:'<'+Buffer.from(row.id).toString('hex')+'@'+new URL(process.env.APP_URL||'http://localhost').hostname+'>'});await tx.query('UPDATE outbox SET sent_at=now(),attempts=attempts+1 WHERE id=$1',[row.id]);}catch{await tx.query("UPDATE outbox SET attempts=attempts+1,available_at=now()+interval '15 minutes' WHERE id=$1",[row.id]);console.error(JSON.stringify({level:'error',event:'email.delivery_failed',id:row.id}));}return true;});if(!worked)break;}transport.close();}
 await db().query('DELETE FROM sessions WHERE expires_at<now()');await db().query('DELETE FROM reset_tokens WHERE expires_at<now()');await db().query('DELETE FROM verify_tokens WHERE expires_at<now()');await db().query('DELETE FROM rate_limits WHERE expires_at<now()');
}
async function main(){do{try{await cycle();}catch{console.error(JSON.stringify({level:'error',event:'worker.cycle_failed'}));}if(process.argv.includes('--once'))break;await new Promise(r=>setTimeout(r,60000));}while(true);process.exit(0);}void main();
